# .github/workflows/ci.yml
name: Testa och bygg Node.js-app

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Klona repot
      uses: actions/checkout@v3

    - name: Installera Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Installera beroenden
      run: npm install

    - name: Kör tester
      run: npm test

    - name: Bygg Docker-image
      run: docker build -t nodetest .

    - name: Logga in i Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Pusha image
      run: |
        docker tag nodetest ${{ secrets.DOCKER_USERNAME }}/nodetest:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/nodetest:latest